### ISSUE TITLE
BRAINSTORMING

### ISSUE THREAD

**Issue by EnzoDiazDev** [faztcommunity/xfazt-bot#10]
El típico espacio de brainstorming.
*Issue fijado, siempre abierto.*

### Reglas:
* El comentario debería ser más o menos:
```
[Descripcion de la idea]
[El por qué de la idea]
Nivel de importancia: [muy alto, alto, medio, bajo]
```
* No opinar con comentarios
No es un espacio para opinar si sí o si no, para eso se creará un issue sobre la idea en cuestión. Usa las reacciones si una idea te entusiasma.

* Reaccionar:
:+1: Para like
:eyes: Para interesante (neutral)
:rocket: Para cuando la idea se haya convertido en un issue.
*(no usar dislikes)*

Nota: Nunca son suficientes ideas, coloquen todo lo que piensen.

**Comment by leandiez** [comment]
## Detectar cuando se ingresa a un canal de voz para iniciar reuniones.

La idea sería que dado un canal de texto y uno de voz, vinculados a un equipo de trabajo (dado por un rol), cuando alguien ingrese al canal de voz, se envie una notificacion al canal de texto arrobando al rol del equipo informando que se dio inicio a una reunion.

Importancia: media

**Comment by urienix** [comment]
### Comando para devolver lista de paises con su hora según parámetros.
---

La idea es que cuando alguien ejecute el comando, agregue la hora y su zona horaria o pais como parámetro y en base a esto devuelva un mensaje con las horas respectivas de cada pais, la idea es algo simple pero muy útil a la hora de programar reuniones ya que con un simple comando podrás ver una lista de paises con la hora correspondiente a cada uno.

#### Ejemplo
---
>>timezone(19:00, Argentina)
- Mexico y Honduras: 16:00
- Perú y Colombia: 17:00
- Rep. Dominicana: 18:00
- España: 01:00

Importancia: bajo

**Comment by JonatanHN** [comment]
# Crear un comando para compartir código

Por medio de un comando que devuelva el código en md.


Ejemplo: 

![Screenshot_20201201-224223.png](https://user-images.githubusercontent.com/36695143/100829496-1d9b0680-3427-11eb-83e5-cacf0b9e90c7.png)

**Comment by Blopaa** [comment]
un comando para hacer sorteos entre otras cosas la importancia es que las reacciones con el evento puedan ser puestas en cualquier mensaje y sin necesidad de usar db
