### ISSUE TITLE
Se requiere comando Ban

### ISSUE THREAD

**Issue by DavichoStar** [faztcommunity/xfazt-bot#20]
### Comando Ban
* Como: *Moderador*,
* Quiero: *Banear un usuario del servidor*,
* Para Poder: *Prohibir su acceso al mismo permanentemente o por un tiempo definido*.
* Prioridad: *Alta*

### Detalles
Considerando que los usuarios suelen no cumplir las reglas y se necesita prohibir a esos usuarios pero informar el motivo de su baneo, el bot le mandaría la razón y el tiempo, si es el caso, de la prohibición al servidor.
Tendría tres propiedades:
- Usuario: Que sería por mención o ID.
- Tiempo: Que sería opcional y con ayuda de dependencias como [ms](https://www.npmjs.com/package/ms) se pondría tiempo como `1h`, `5d`, `1y`.
- Razón: Que sería el motivo por el cuál se dio el baneo. Esta propiedad puede ser debatible si es opcional u obligatorio.

Ejemplo: `!ban <@usuario> <razón>`, `!ban <ID> <razón>` o `!ban <@usuario> <tiempo> <razón>`

**Comment by EnzoDiazDev** [comment]
> Cambiaría el rol de administrador a moderador. 
No teniendo en cuenta los roles personalizados del servidor, sino lo que Discord considera como mod. Para Discord, administrador es el que tiene poder total del servidor, y son apenas tres.

_Originally posted by @EnzoDiazDev in https://github.com/faztcommunity/xfazt-bot/issues/19#issuecomment-748639988_
