### ISSUE TITLE
[DISCUSION] Dependencias y otros archivos base

### ISSUE THREAD

**Issue by leandiez** [faztcommunity/xfazt-bot#8]
# [DISCUSION] Dependencias y otros archivos base

## Descripción de la funcionalidad

> Abro este topic para ver con que dependencias trabajaremos la primer version del bot.

## Propuesta de implementación
> En principio tengo entendido que utilizaremos Discord.JS y linter. 
> Se aceptan ideas de librerias u otras funcionalidades que puedan ayudar a construir el código.
>
>
Actualizacion 23/11:
### Entorno productivo:
- Discord.JS: Libreria-API para acceder a Discord
- @discordjs/opus : Libreria para soporte de voz al Bot
- cross-env "Sincronizador" variables de entornos para unificar tipos de Windows o Unix
- dotenv: manejo de archivo .env para variables globales del proyecto
- TypeScript, @types/node: Dependencias varias para funcionamiento TS en Node
- TS-Node: Automatizacion de compilacion TS en Node

### Entorno desarrollo
- Discord.JS: Libreria-API para acceder a Discord
- @discordjs/opus : Libreria para soporte de voz al Bot
- Eslint: Reglas de codeo
- Nodemon: Automatizacion de gestion WebServer-Dev
- TS-Node: Automatizacion de compilacion TS en Node
- TypeScript, @types/node, @typescript-eslint: Dependencias varias para funcionamiento TS en Node
- cross-env "Sincronizador" variables de entornos para unificar tipos de Windows o Unix
- dotenv: manejo de archivo .env para variables globales del proyecto

**Comment by JonatanHN** [comment]
Nodemon

**Comment by leandiez** [comment]
> 
> 
> Nodemon

Esto seria para el entorno dev cierto? 

Planteo otro tema, la idea seria dividir las dependencias que usariamos para dev y otras dependencias para build.

De momento tendriamos esto:

build: discord.js

dev: todo lo de build + linter y nodemon.

**Comment by omairapalacios** [comment]
En las primeras reuniones también se comentó el tema de probar los comandos que se implementen en el bot  de manera automatizada usando algún framework, en este caso jest https://jestjs.io/ y sería una dependencia de desarrollo.

**Comment by EnzoDiazDev** [comment]
el repo trae por plantilla las dependencias de desarrollo "husky", "prettier" y "ts-node".
tsnode está muy buena y se puede combinar con nodemon para saltar los pasos de compilación en desarrollo. 
Prettier y husky son para arreglar y verificar el codigo, pero no sé precisamente como se configuran. 

Podríamos dejarle la tarea de arreglar y configurar las dependencias (incluyendo eslint, typescript, etc) a alguien. 

Si alguien tiene experiencia con estos scripts que avise :linksuccess:

**Comment by urienix** [comment]
¿Por cierto, como estará la distribución de archivos? me refiero a como estarán distribuídas las carpetas dentro de src, he revisado varios bots y casi todos tienen una estructura diferente, pero no se si hay una estructura determinada con la que recomienden trabajar o nos guiaremos con la estructura de los ejemplos de Lottie

**Comment by EnzoDiazDev** [comment]
> ¿Por cierto, como estará la distribución de archivos? me refiero a como estarán distribuídas las carpetas dentro de src, he revisado varios bots y casi todos tienen una estructura diferente, pero no se si hay una estructura determinada con la que recomienden trabajar o nos guiaremos con la estructura de los ejemplos de Lottie

Parte de la idea de crear primero una clase bot antes de el bot en sí es poder desarrollar un estandar para la creación de bots (no solo en discord, en cualquier ambiente) porque la verdades que no hay muchos estandares para seguir, como sí lo hay en servidores de express o backend en general. 

La idea es que cada comando sea una clase con decoradores. Siguiendo las practicas de toda la vida, un archivo exporta por defecto una clase del mismo nombre del archivo, o una funcion del mismo nombre del archivo. 
Cuando se trata de funciones, se pueden añadir funciones extra en el mismo que son exportadas también. 
Teniendo en cuenta que cada comando es una clase con decoradores, el archivo se llamara como el comando (y como la clase), e importará todos los decoradores. 

Más o menos algo como
```
-src/
    -decorators/
        -permissions/
            -Admin.ts
            -SendMessages.ts
            - ...
    -commands/
        -Kick.ts
        -...
    -bot/
        -Bot.ts
        -...
    -database/
        -...
```

**Comment by leandiez** [comment]
> 
> 
> el repo trae por plantilla las dependencias de desarrollo "husky", "prettier" y "ts-node".
> tsnode está muy buena y se puede combinar con nodemon para saltar los pasos de compilación en desarrollo.
> Prettier y husky son para arreglar y verificar el codigo, pero no sé precisamente como se configuran.
> 
> Podríamos dejarle la tarea de arreglar y configurar las dependencias (incluyendo eslint, typescript, etc) a alguien.
> 
> Si alguien tiene experiencia con estos scripts que avise :linksuccess:

Yo que estoy iniciandome en todo el mundo JS me parece un buen puntapie para arrancar, manejar NPM y scripts de configuracion. Me ofrezco para hacerlo.

En cuanto a la estructura la podria ir modelando tambien y la mando junto con las dependencias en un PR para terminar de ajustar detalles.

Este ISSUE lo dejaría abierto un tiempo hasta que comencemos a meter mano al código propio del BOT asi si surje alguna otra idea en el medio todos pueden aportar.

**Comment by ElaxDev** [comment]
¿Qué dependencia vamos a usar para la base de datos? Estaba pensando en Mongoose para usar MongoDB pero no sé si ustedes tengan alguna idea u otras cosas en mente.

**Comment by EnzoDiazDev** [comment]
Sobre la base de datos ya lo habíamos hablado. 
Las peticiones se hacen a una API de juguete con una base de datos en firebase (porque es bien facil de configurar)
Luego cuando la api de faztcommunity esté lista, cambiamos la url de la api y listo.

**Comment by leandiez** [comment]
> Sobre la base de datos ya lo habíamos hablado.
> Las peticiones se hacen a una API de juguete con una base de datos en firebase (porque es bien facil de configurar)
> Luego cuando la api de faztcommunity esté lista, cambiamos la url de la api y listo.

Ojo con esto al momento de hacer las llamadas. Habria que tener en cuenta dejar en el .env la URL y luego replicar los mismos endpoints. Eso por ahi se puede tratar en otro ISSUE para definir bien como trabajariamos esa parte.

**Comment by EnzoDiazDev** [comment]
Yo los aliento ustedes a que usen los issues para que vayan organizandose sin mi. Yo me encargo de aceptar y arreglar sus pull request, además voy armando la api
Para el tema de la url, como solucion en el .env usamos un jwt para validar nuestra identidad. Eso va a ser un poco más práctico y seguro. Tengo una api modelo para esto así que la voy a hacer rapidito.
